language: python
python:
- '3.5'
install:
- pip install slackclient
- pip install urllib3
- pip install RPi.GPIO
- pip install emoji
script: "./unittests"
notifications:
  slack:
    secure: VnGm8+FlYK4sqIVR1O/Y2WlZiE0QZnoRnzs1yWfHGvzL4Yqxs05X2/fmvDZNJ+EB4e2rdqKCA+MOUCdppg6l7xQbBSMJgbjL7Uatw7RnNczziarHIP4gvOmwQzzJkJTEMXsh5es7X0Bjp0Q4KhUqhU4MftUWLJMEaZWdW5q5houwaNODkC1pg7cWAuCwjjVBJXj5LJG9LNHvtF9G9iQtdgdRckorQafk+v+SUR5N7NwBgrG6bAqLZgPXtG7UiKGFBdJ5udbahKYrogV8Ne+n0QVllbU/5MQBp8xcbfENJ6fTEHUEksuzMiAjCX1IQMrUXe0QFflhiSDIjEGDiP2O3klYOaXMruS4+CpfGK67Z+5j6RQzn1Rdrg3F2veVBz7YQTBwZzvcv/y5Ep/mlRsk8DKDXuVN2Lh+WxGGq1gZAlKYdcNd+cNYx+E2f/RnRwYsNy5LT9B9O86upBNwWr5k8S5I6H5S3Ui8KwcelTrDuSb7hdxa+clrIouR2usPU7wdl7/1eP0LnAjSbaA+Dn2SaOLWh6HSA7/GrkJPqdvMlVoDx9RxNW60HErGqEBBqEPlPXzf3QZZWTSV+TR96/4holb9mXJBLjuYabXUmq3Lz+6hBLFH/I5kV3PaLqjmE5D+4oDp0gcQF1oKfzbTRTDFeAPWNTXiPfqJbdlGYOnwrlQ=
deploy:
  on:
    all_branches: true
  provider: pypi
  skip_cleanup: true
  user: wray
  password:
    secure: N7wHjqKO6lwNuMXM6F94byfqgAgbAEBQr3t1OqMELR7RgKS+tfGSZD8ssnq0Ks5fWfNiQqiM0PZjXZi02h00mHvYUj84lCsFiDClK7ZZs+wrsQthk05qN5UMzsGswYL9EH/DC2v6+UGuDcOPLFnPsNViknita4I1/oofoQ33sixwOo/nFtt+mIk6BWqoYE/CbbhNBvj+mehNvzSiGHYFF3O+98sktH3DOnMYLpaGfuwhymLg/T72RgCNfey4t4k+KiHud+IF2UEGy4dz13XYKdCWo4Th8L1hypXMWB4I9IqGXaBYyRC1ztTI3gIOXsF2LFVeRF6VELoIlylW44yOaEpm1Qu6kMcJt+bfCxClkEFcK27YhvaE7YKBXdb8vPfr7TzHdQVBs9ubqHCeJR6H2S//q4PlqptB94Dcu6whMdo8Kf/zuRFgfnXULpsbdeT2N4cO560QmoWK5d9qVt8Z8TVtwSE/C+tA0JzHV9lXzgG9Qi1+T5pRfwRjQ6qTEBuTXf2C2c09+LP70o5wfgn3Pv0vJhXRVf16MTZjVx7hS9XRvlnOMxBb90v2bRmAt5Jo7uoXfKSF5TdtPXDDTD06vdu7heyW5M2a+JvauqCUZzp6bGx19drROg4WBdxye/fiGp7K5bSJ003mHCjLHRamY/NYZWkUh6ba29orqzO8rhA=
