#!/bin/sh

# Be careful, this will kill all running python processes!
killall python 

python3 -m pip install --upgrade --user slackbot_wems

export SLACK_BOT_TOKEN=${your_slack_bot_token}

python3 -m slackbot_wems.slackpi
