#!/bin/sh
# This is the script that cron will run
# On our Raspberry Pi we have configured cron to run it every 5 minutes

# Be careful, this will kill all running python processes!
killall python 
# Grab the latest version of slackbot_wems from PyPi
python -m pip install --upgrade --user slackbot_wems
# Declare an environment variable with your Slack bot token in
export SLACK_BOT_TOKEN="insert-slack-bot-token"

# Start the bot
python -m slackbot_wems.slackpi
