#!/bin/sh

# Be careful, this will kill all running python processes!
killall python 

pip install --upgrade slackbot_wems

export SLACK_BOT_TOKEN=${your_slack_bot_token}

python -m slackbot_wems.slackpi
